### ISSUE TITLE
Format date and time the same way

### ISSUE THREAD

**Issue by goagex** [gehaxelt/python-rss2irc#19]
New feature request:

Get the date and time stamp the same, from all rss feeds.
Right now I see:
Mon, 29 Aug 2016 00:00:00 +0000
Mon, 29 Aug 2016 03:33:33 GMT
2016-08-29T17:59:00Z
2016-08-29

Would be nice to have it converted to a single stamp at UTC time.
Preferably before insert to database.
Extra great if date format could be configured in config.py

**Comment by gehaxelt** [comment]
Good idea, I'll see what I can do after vacation.

**Comment by goagex** [comment]
Hi!

I dont know if you noticed, but I created a Pull Request to fix the date
format =)

Kind regards /
Jonas

2016-08-31 18:08 GMT+02:00 Sebastian Neef notifications@github.com:

**Comment by gehaxelt** [comment]
Hi,
sorry, I missed it. I'm quite busy this week.

**Comment by goagex** [comment]
Hi again!

Thanks for the merge, I just learned how Github works yesterday.
If it's ok I will make a few other changes.

What I think of right now:

1: Make colors optional, as it fuckes up my irssi right now =)
Perhaps something like this, to make it a bit clearer:

Original: Packet Storm: Kaspersky FileManager Cross Site Scripting,
http://tinyurl.com/hmhzyez, 2016-09-01 10:59:07 +0000

My format: [Packet Storm]: Kaspersky FileManager Cross Site Scripting |
http://tinyurl.com/hmhzyez | [2016-09-01 10:59:07 +0000]

Colors will still be available via config.py of course.

2: Rewrite the code to be more 'pythonic'
I'm really not a good python code writer, but I like to make it clean.
If its ok I would like to to something like this example:
Original bot.py:
connection.privmsg(self.__config.CHANNEL, "Hi, I'm " +
Colours('3',str(connection.get_nickname())).get() + " your bot. Send " +
Colours(self.num_col,"!help").get() +" to get a list of commands.")

My edited bot.py:
bot_name = Colours('3',str(connection.get_nickname())).get()
bot_help = Colours(self.num_col,"!help").get()

bot_msg = ("Hi, I'm {}, your bot. Send {} to get a list of commands."
                  .format(bot_name, bot_help))

connection.privmsg(self.__config.CHANNEL, bot_msg)

What do you think of these changes?

Kind regards / Jonas

2016-09-05 21:21 GMT+02:00 Sebastian Neef notifications@github.com:

**Comment by gehaxelt** [comment]
Hi,

sure, go ahead!

All the best,
gehaxelt
