### ISSUE TITLE
TracebackError

### ISSUE THREAD

**Issue by rinzes** [gehaxelt/python-rss2irc#20]
I don't understand why I am getting this. It worked before... I've looked everywhere for irc.client

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from bot import Bot
  File "/home/znc/python-rss2irc/bot.py", line 5, in <module>
    import irc.client

**Comment by goagex** [comment]
Just tried a new virtual env, and it works here.
Debian 8 / Python 2.7.9

Can you paste your output of 'pip freeze' please.

**Comment by rinzes** [comment]
(venv) znc@dvanet:~/python-rss2irc$ pip freeze
inflect==0.2.5
irc==14.2.2
jaraco.classes==1.4
jaraco.collections==1.4.1
jaraco.functools==1.12
jaraco.itertools==1.7.1
jaraco.logging==1.5
jaraco.stream==1.1.1
jaraco.text==1.8
more-itertools==2.2
pytz==2016.6.1
six==1.10.0
tempora==1.4

**Comment by goagex** [comment]
seems that you are missing some of the packages?
Not the one related to irc tho, my pip freeze:
backports.functools-lru-cache==1.2.1
feedparser==5.2.1
inflect==0.2.5
irc==14.2
jaraco.classes==1.3
jaraco.collections==1.3.2
jaraco.functools==1.11
jaraco.itertools==1.7.1
jaraco.logging==1.3.1
jaraco.stream==1.1
jaraco.text==1.6.3
more-itertools==2.2
pytz==2016.4
six==1.10.0
sqlite3worker==1.0
tempora==1.4
TinyUrl==0.1.0

Can you try to re-run:
pip install -r requirements.txt

**Comment by rinzes** [comment]
Sorry dummy me was in the WRONG server.
