### ISSUE TITLE
Disconnects after some time

### ISSUE THREAD

**Issue by jcharaoui** [gehaxelt/python-rss2irc#22]
I'm using the bot on the OFTC IRC network and after the one or two days, the bot gets disconnected and has to be restarted. I tested modifying the code to use the `irc.bot.SingleServerIRCBot` class instead and so far it works much better, the bot automatically reconnects and stays online.

**Comment by gehaxelt** [comment]
Thanks! 
I'll have a look at this later this evening and probably push a fix for it.
