### ISSUE TITLE
Add configuration option to avoid flooding channel with on_join function

### ISSUE THREAD

**Issue by leifmadsen** [gehaxelt/python-rss2irc#29]
Currently whenever someone joins a channel, the `on_join` function is called, which can cause flooding to the channel. An option should be added to avoid spamming the channel, or maybe I've identified a bug, and the message should be messaged to the joiner privately instead of sending into the channel.

**Comment by gehaxelt** [comment]
Hmm... I thought that this event is only triggered when the bot joins the channel. However this [might not be the case](https://pythonhosted.org/irc/irc.html#irc.client.SimpleIRCClient):

> The method on_join will be called when a “join” event is created (which is done when the server sends a JOIN messsage/command)

I'll label this as a bug for now, but maybe we can use this behaviour to solve #30 by sending a private message to the newly joined user?

**Comment by h4ck3rm1k3** [comment]
yes the same
