### ISSUE TITLE
Add SSL support to a python irc bot

### ISSUE THREAD

**Issue by jcharaoui** [gehaxelt/python-rss2irc#3]
SSL support would be useful, as some networks/channels require it.

**Comment by gehaxelt** [comment]
Hi @jcharaoui , 
the irc-module seems to support SSL connections (https://pythonhosted.org/irc/irc.html?highlight=ssl) - I'll have a look in the next couple of days.

**Comment by adongy** [comment]
Can i take this issue ?

**Comment by gehaxelt** [comment]
@adongy Sure and thanks for the PR!
