### ISSUE TITLE
Install/Use on AmazonAWS

### ISSUE THREAD

**Issue by rinzes** [gehaxelt/python-rss2irc#34]
I have installed python-rss2irc on a Amazonaws instance and can't seem to get it to connect to the internet. I have added TCP/UDP port 6667 anywhere to the security group. Any help would be appreciated

**Comment by gehaxelt** [comment]
Hi,
I'm not sure if I can help you with that. Did you check...
- that the `config.py` file exists?
- that the host, port, ssl, channel options in the `config.py` are correct?
- that you can connect to other services on the internet?

**Comment by rinzes** [comment]
Yes, all is correct. I thought maybe there was another port beside 6667, 6697 & 993 that I need to open. It works ok when I installed and setup on Atlantic Cloud server. I was just hoping to use on AmazonAWS

**Comment by gehaxelt** [comment]
Hi,
sorry to hear that, but I don't have an idea why it should not work on AWS? I can't believe that AWS is blocking outgoing IRC traffic...

I'll close this for now.
