### ISSUE TITLE
Adding on_kick function

### ISSUE THREAD

**Issue by Wibol** [gehaxelt/python-rss2irc#48]
This works for me in bot.py, IRCBot class:
```
    def on_kick(self, connection, event):
        """Join the correct channel again"""
        if irc.client.is_channel(self.__config.CHANNEL):
            time.sleep(31)
            connection.join(self.__config.CHANNEL)

```

**Comment by gehaxelt** [comment]
@Wibol Would you mind creating a PR for this?

**Comment by Wibol** [comment]
I guess PR is a Pull Request ... I'm not a programmer and I do not know how Github works. I only copy and paste from other bots. I sent it for you to insert it into your bot, please.

I feel the discomfort.

**Comment by gehaxelt** [comment]
@Wibol Sorry for the delay on this one. 

I've added the change now :-)
