### ISSUE TITLE
Adding IRC nick login support

### ISSUE THREAD

**Issue by Wibol** [gehaxelt/python-rss2irc#49]
This works for me:

Added to config.py, Config class:
`self.NICKPASS = ""`

Changed on_welcome function in bot.py, IRCBot class to:
```
    def on_welcome(self, connection, event):
        """Login"""
        if self.__config.NICKPASS:
            self.connection.privmsg("NickServ", "IDENTIFY {}".format(self.__config.NICKPASS))
        """Join the correct channel upon connecting"""
        if irc.client.is_channel(self.__config.CHANNEL):
            connection.join(self.__config.CHANNEL)
```

**Comment by gehaxelt** [comment]
@Wibol Do you mind creating a PR for this change?

**Comment by Wibol** [comment]
I guess PR is a Pull Request ... I'm not a programmer and I do not know how Github works. I only copy and paste from other bots. I sent it for you to insert it into your bot, please.

I feel the discomfort.

**Comment by gehaxelt** [comment]
@Wibol Okay, don't worry. I'll create the PRs when I'll find the spare time for it and let you review them :-)
