### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by sachaz** [gehaxelt/python-rss2irc#56]
Hey ! is any form of life here ?

**Comment by Wibol** [comment]
Four months without response. Too much work, I guess.

**Comment by gehaxelt** [comment]
Hi, 
I'm super busy and sometimes miss notifications. Sorry for that. 

That being said, I don't have a lot of spare time to work on this project. I'll try to approve PRs nonetheless, so feel free to port it :-) 

If I remember correctly, there was a reason for choosing python2. I think back then one library was not python3 ready or so, but I could be mistaken here.

**Comment by ssbarnea** [comment]
I was looking for a python bot for integrating rss into irc but sadly https://pythonclock.org/ and that is is for real. I do not want to invest time in any project that would become unmaintainable in few months. 

Maybe it would worth adding a banner like "open for adoption", we may find people that could work on that.

**Comment by gehaxelt** [comment]
Yeah, I see a point here. 

I'll try to find time to make a rewrite to python3, but on the other hand I'm always happy to merge PRs that fix and maintain/update the project :-)

**Comment by ssbarnea** [comment]
@gehaxelt Sure. Now that I am using it I will probably start adding PRs. Usually adding py3 support should be made in smaller chunks, as they are easier to review.

PS. I would avoid rewrite, I am more of transition, with some time covering both. Also this is good as the same process can later be used to test newer versions of python.

**Comment by Wibol** [comment]
I have just translated the bot to Python3 and it uses the latest libraries available. I would like some users to help me test it on different systems before making the Pull Request, as this is a major change.

The Python3 edition of the bot and the new installation instructions are available at [my repository](https://github.com/Wibol/python-rss2irc). You can still use your current "feeds.sql" file, but the database needs to be recreated, so it would be advisable before running it:

mv feeds.db feeds.db.old

Thanks.

Translated with www.DeepL.com/Translator (free version)

**Comment by gehaxelt** [comment]
#62 was just merged. Thank you @Wibol for the contribution!
