### ISSUE TITLE
Make URL shortening optional

### ISSUE THREAD

**Issue by jcharaoui** [gehaxelt/python-rss2irc#6]
There are privacy implications in using these third party services, and sometimes it's just not needed. Please implement an option to switch it off.

**Comment by gehaxelt** [comment]
Hey @jcharaoui , 
thanks for all the issues. 
I'll be on vacation for the next couple of weeks, so don't expect fixes in the near future. But I'll have a look at them, when I'm back. 

Feel free to open PRs in the meantime if you feel like it. 

All the best,
gehaxelt
