### ISSUE TITLE
Bot Postings

### ISSUE THREAD

**Issue by rinzes** [gehaxelt/python-rss2irc#8]
The postings are ok in mIrc but in hexchat they get displayed as follows:

 [032mFC[0m: Silver Standard Resources options imply 4.2% move in share price post-earnings, below median historical move, [1;37mhttp://tinyurl.com/gq5lg7o[0m, [1;30mWed, 10 Aug 2016 15:19:04 -0400[0m
<Sopel> [032mFC[0m: Defensive play in Teck Resources as shares tick higher, [1;37mhttp://tinyurl.com/zofn3hf[0m, [1;30mWed, 10 Aug 2016 15:20:06 -0400[0m

**Comment by gehaxelt** [comment]
Should be fixed by #12
