### ISSUE TITLE
Multi Use

### ISSUE THREAD

**Issue by rinzes** [gehaxelt/python-rss2irc#9]
Would like to see the abilty to use multi server use using diff config and add the feed.sql file name within the config.

ie: Server 1 = server1.py 
     Server 1 = server2.py

**Comment by gehaxelt** [comment]
Hi,
can't you just simply copy the code to another directory and run it with a different configuration? 
It's not a nice solution, but a workaround until this is implemented.

**Comment by rinzes** [comment]
Already done :)

**Comment by gehaxelt** [comment]
I think I'll close this as I think that running multiple separate instances is the better idea for now.
